name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJS
        run: echo "Done - bye!"
      - name: List command
        run: ls -l
      - name: Branch command
        run: echo "Raw branch = $(Build.SourceBranch)"
      - name: Raw Branch
        run: echo "Raw branch = $(Build.SourceBranch)"
      - name: CR brch
        run: echo "Cleaned branch = $branch"
        
      
        
        
        
